/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_greatcompany_myteam_ref_JNITest */

#ifndef _Included_com_greatcompany_myteam_ref_JNITest
#define _Included_com_greatcompany_myteam_ref_JNITest
#ifdef __cplusplus
extern "C" {
#endif
#undef com_greatcompany_myteam_ref_JNITest_COMMAND_CHANGE_TITLE
#define com_greatcompany_myteam_ref_JNITest_COMMAND_CHANGE_TITLE 1L
#undef com_greatcompany_myteam_ref_JNITest_COMMAND_UNUSED
#define com_greatcompany_myteam_ref_JNITest_COMMAND_UNUSED 2L
#undef com_greatcompany_myteam_ref_JNITest_COMMAND_TEXTEDIT_HIDE
#define com_greatcompany_myteam_ref_JNITest_COMMAND_TEXTEDIT_HIDE 3L
/*
 * Class:     com_greatcompany_myteam_ref_JNITest
 * Method:    initSDL
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_greatcompany_myteam_ref_JNITest_initSDL
  (JNIEnv *, jclass);

/*
 * Class:     com_greatcompany_myteam_ref_JNITest
 * Method:    convertBytesToVideo
 * Signature: ([B[B[B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_greatcompany_myteam_ref_JNITest_convertBytesToVideo
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     com_greatcompany_myteam_ref_JNITest
 * Method:    destroySDL
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_greatcompany_myteam_ref_JNITest_destroySDL
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
